import { Inter } from 'next/font/google'
import { Theme, ThemePanel } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Theme appearance='dark' accentColor='green' grayColor='gray'>
          {children}
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  )
}
